repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: trailing-whitespace
    rev: "v5.0.0"
  - repo: https://github.com/psf/black
    hooks:
      - id: black
    rev: "25.1.0"
  - repo: https://github.com/PyCQA/isort
    rev: "6.0.0"
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: "7.1.1"
    hooks:
      - id: flake8